# Домашнее задание по теме «Табличные данные и визуализация»

В этом задании ты изучишь датасет Student Depression. Надеемся, что выводы, которые ты сделаешь после анализа датасета, пригодятся в реальной жизни!

Обрати внимание, что около каждой задачи указано количество баллов, которое можно получить за её выполнение.

> ### Правила домашнего задания
>1. Нельзя удалять существующие ячейки кода.
>
>2. Можно добавлять и дописывать свои ячейки.
>
>3. Место, куда тебе нужно написать код, помечается комментарием.
>
>
> 4. Ответ без кода, который подтвердит твоё решение, не засчитывается. Исключение — задачи и вопросы, где код не требуется и нужно сделать вывод из известных данных.
>
 > 5. Код должен быть работоспособным. У проверяющих должна быть возможность воспроизвести все полученные результаты.
>
> 6. Все графики подписывай так, чтобы можно было легко понять их суть. Избегай слишком мелкого или крупного текста, подписывай оси на одном языке.

## Установка библиотек

In [1]:
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

## Задание 1 [1 балл]

Необходимые данные хранятся по [ссылке](https://drive.google.com/file/d/1WdZxvQQQH9MGTOH2yIjjewd0KuEsrZvl/view?usp=drive_link). Загрузи их в ноутбук.

1. Воспользуйся командой `gdown` для загрузки данных **[0 баллов]**.
2. Считай датасет в pandas dataframe **[0,2 балла]**.
3. Выведи датасет на экран **[0,3 балла]**.
4. Исключи переменную `id` или сделай её индексом. Можешь выбрать любой вариант **[0,5 балла]**.

In [2]:
# 1. Загрузи файл
!gdown 1NiF28k5POrZsofchU6k0X1AR3OCVJl4s

Downloading...
From: https://drive.google.com/uc?id=1NiF28k5POrZsofchU6k0X1AR3OCVJl4s
To: /content/Student Depression Dataset.csv
100% 2.81M/2.81M [00:00<00:00, 134MB/s]

In [3]:
# Считай датасет
df = pd.read_csv("Student Depression Dataset.csv")

In [4]:
# Вывод датасета
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [5]:
# Преобразуй переменную id
df = df.set_index("id")

## Задание 2 [3 балла]

Проведи первичный анализ данных.

1. Выведи информацию по типам данных каждой колонки **[0,5 балла]**.
2. Выведи информацию по NaN-значениям. Если они есть, напиши, как их можно заполнить **[0,5 балла]**.
3. Построй описательные статистики для числовых переменных (максимальное и минимальное значение, среднее) и напиши по ним выводы **[1 балл]**.
4. Сделай описательные статистики для нечисловых переменных (количество уникальных элементов, наиболее популярный представитель) **[1 балл]**.

В пунктах 3–4 тебе может помочь [документация](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html).

In [6]:
# 1 Вывод информации о типах данных
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27901 entries, 2 to 140699
Data columns (total 17 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gender                                 27901 non-null  object
 1   Age                                    27901 non-null  float64
 2   City                                   27901 non-null  object
 3   Profession                             27901 non-null  object
 4   Academic Pressure                      27901 non-null  float64
 5   Work Pressure                          27901 non-null  float64
 6   CGPA                                   27901 non-null  float64
 7   Study Satisfaction                     27901 non-null  float64
 8   Job Satisfaction                       27901 non-null  float64
 9   Sleep Duration                         27901 non-null  object
 10  Dietary Habits                         27901 non-null  object
 11  Degree                                 27901 non-null  object
 12  Have you ever had suicidal thoughts ?  27901 non-null  object
 13  Work/Study Hours                       27901 non-null  float64
 14  Financial Stress                       27898 non-null  float64
 15  Family History of Mental Illness       27901 non-null  object
 16  Depression                             27901 non-null  int64
dtypes: float64(8), int64(1), object(8)
memory usage: 3.8+ MB

In [7]:
# 2 Вывод информации о NaN
print(f"Кол-во NaN: {df.isna().sum().sum()}")

Кол-во NaN: 3

**Анализ NaN-значений**

Поскольку NaN-значения присутствуют только в числовом столбце, причем с диксретными значениями, а именно **целые** числа от 1 до 5, то можно дозаполнить пропуски медианой / средним или интерполировать с помощью `df.interpolate`

In [8]:
# 3 Описательная статистика числовых переменных
df.describe().loc[["max", "min", "mean"]]

,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress,Depression
max,59.0000,5.000000,5.00000,10.000000,5.000000,4.000000,12.000000,5.000000,1.000000
min,18.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
mean,25.8223,3.141214,0.00043,7.656104,2.943837,0.000681,7.156984,3.139867,0.585499

Напиши выводы по описательной статистике числовых переменных.

In [9]:
# 4 Описательная статистика нечисловых переменных
df.describe(include=["O"]).loc[["unique", "top"]]

,Gender,City,Profession,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Family History of Mental Illness
unique,2,52,14,5,4,28,2,2
top,Male,Kalyan,Student,Less than 5 hours,Unhealthy,Class 12,Yes,No

Напиши выводы по описательной статистике нечисловых переменных.

## Задание 3 [4 балла]

Проведи разведочный анализ данных.

### Шаг 1 [2 балла]
Нарисуй гистограмму распределений целевой переменной `Depression` и гистограмму распределений признаков **[0,5 балла]**.

Проанализируй полученные графики **[1,5 балла]**.

Ответь на следующие вопросы как минимум для двух признаков.

1) Какое распределение у признака, и почему оно именно такое?

2) Есть ли выбросы? Чем они могут быть вызваны?

In [10]:
axes[0].bar(value_counts.index.astype(str), value_counts.values,
            color=['lightblue', 'salmon'], edgecolor='black', width=0.6)

NameError: name 'axes' is not defined

Проанализируй полученные графики и ответь на вопросы.

### Шаг 2 [1 балл]
 Нарисуй рядом две гистограммы.
  * Слева: гистограмма продолжительности сна.
  * Справа: гистограмма продолжительности сна, где каждая категория должна отображаться с учётом переменной `Depression`.
  * Для каждой гистограммы порядок колонок упорядочи  от минимальной продолжительности сна до максимальной. Категорию `Others` помести в начало или конец.

  Что можно сказать по полученным графикам?

In [ ]:
# Напиши код здесь

Проанализируй полученные графики.

### Шаг 3 [1 балл]


Построй корреляционную матрицу. Выбери две самые сильные корреляции (по модулю) и попробуй объяснить возможные причины этих связей.

In [ ]:
# Напиши код здесь

Проанализируй корреляционные матрицы.

## Задание 4 [2 балла]

Выбери две модели машинного обучения. Список наиболее популярных можно посмотреть в семинаре.

- Обработай категориальные переменные **[0,5 балла]**.

- Раздели выборку на обучающую и тестовую **[0,5 балла]**.

- Обучи две модели **[0,5 балла]**.

- Измерь качество моделей по метрике Accuracy **[0,5 балла]**.

  Метрика Accuracy считает среднюю долю верных ответов и выглядит так:

$$Acc = \frac{1}{n}∑_{i=1}^nI[y_i = \hat{y_i}]\text,  \\
\text{где n — количество наблюдений;} \\
y_i \text{ — истинная метка класса для i-го наблюдения;} \\
\hat{y_i} \text{ — предсказанная метка класса для i-го наблюдения.}\\
I[y_i = \hat{y_i}] = 1, если\;y_i = \hat{y_i}. Иначе\;I[y_i = \hat{y_i}] = 0$$

In [ ]:
# Подготовка датасета

# 1. Разделение данных на признаки (X) и целевую переменную (y)

# 2. Разделение данных на обучающую и тестовую выборки

In [ ]:
# 3. Обучение первой модели

# 4. Предсказания на тестовой выборке

# 5. Измерение Accuracy

In [ ]:
# 6. Обучение второй модели

# 7. Предсказания на тестовой выборке

# 8. Измерение Accuracy

## Проверка гипотез [2 бонусных балла]

Придумай, как можно проверить следующие гипотезы.

1) Студенты с высоким баллом более склонны к мрачным мыслям **[1 балл]**.

2) Студенты получают больше баллов, если продолжают учиться вместо сна **[1 балл]**.

Поясни, как у тебя получились такие выводы. Если используешь график, следи за тем, чтобы все оси были подписаны и графики выглядели аккуратно.

In [ ]:
# Гипотеза 1. Напиши код здесь

In [ ]:
# Гипотеза 2. Напиши код здесь

Напиши выводы по двум гипотезам.